{% set name = "zeromq" %}
{% set version = "4.2.5" %}
{% set sha256 = "cc9090ba35713d59bb2f7d7965f877036c49c5558ea0c290b0dcc6f2a17e489f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/zeromq/libzmq.git
  git_tag: v{{ version }}
  patches:
    - rm-clang-format.patch
    - 0003-windows-install.patch
    - 0005-osx-test.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake                        # [win]
    - make                         # [not win]
    - automake                     # [not win]
    - autoconf                     # [not win]
    - libtool                      # [not win]
    - pkg-config                   # [not win]
  host:
    - libsodium

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a         # [unix]
    - test -f ${PREFIX}/lib/libzmq.so        # [linux]
    - test -f ${PREFIX}/lib/libzmq.so.5      # [linux]
    - test -f ${PREFIX}/lib/libzmq.dylib     # [osx]
    - test -f ${PREFIX}/lib/libzmq.5.dylib   # [osx]
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake  # [unix]
    - ${PREFIX}/bin/curve_keygen  # [unix]
    - if exist %LIBRARY_LIB%\libzmq-mt-s-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\libzmq-mt-{{ version | replace('.', '_') }}.dll (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_LIB%\libzmq-mt-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else (exit 1)           # [win]
    - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0) else (exit 1)    # [win]

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - SylvainCorlay
    - JohanMabille
