{% set name = "zeromq" %}
{% set version = "4.3.4" %}
{% set sha256 = "c593001a89f5a85dd2ddf564805deb860e02471171b3f204944857336295c3e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/libzmq/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - rm-clang-format.patch
    - 0003-windows-install.patch
    - 0005-osx-test.patch  # [osx]

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}  # [not win]
    # Windows DLLs have x.y.z in filename
    - {{ pin_subpackage(name, max_pin='x.x.x') }}  # [win]

requirements:
  build:
    - m2-patch                     # [win]
    - automake                     # [unix]
    - autoconf                     # [unix]
    - make                         # [unix]
    - cmake                        # [win]
    - libtool                      # [unix]
    - pkg-config                   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libsodium

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a         # [unix]
    - test -f ${PREFIX}/lib/libzmq.so        # [linux]
    - test -f ${PREFIX}/lib/libzmq.so.5      # [linux]
    - test -f ${PREFIX}/lib/libzmq.dylib     # [osx]
    - test -f ${PREFIX}/lib/libzmq.5.dylib   # [osx]
    # verify libsodium is linked
    #- otool -L ${PREFIX}/lib/libzmq.dylib | grep sodium  # [osx]
    #- ldd ${PREFIX}/lib/libzmq.so | grep sodium          # [linux]
    - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfig.cmake         # [unix]
    - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfigVersion.cmake  # [unix]
    - ${PREFIX}/bin/curve_keygen  # [unix]
    - if exist %LIBRARY_LIB%\libzmq-mt-s-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\libzmq-mt-{{ version | replace('.', '_') }}.dll (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_LIB%\libzmq-mt-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else (exit 1)           # [win]
    - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0) else (exit 1)    # [win]

about:
  home: http://zeromq.org
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - SylvainCorlay
    - JohanMabille
