travis:
  secure:
    BINSTAR_TOKEN: cmez17FiXlvjK2W/7RThJcBqVzH+2CbisxW3mIjA8mwwP9L98z6ybXGQiKiIzq74ZhJVB23QamFyoo2P2jS9xCE1FCrs2wVZRrUzQwOE0/Ry9+4uUj+c6wWejzi31mpQ2IcOJcAqwYAYO++VI71qJVe6i7w7oNE9cZQo4Vd1maoPNFli0H04hQ8uVEMWHWo/rWbC8l4BTH6vgQafZdwS/RrW2pVUDBOcVJf0iwfmhUe7gE9VquulUYlDsBRjt6X31emxv4vm50Q6TL+aJSxtfUUY5SR+LlfOCS994UYR1xqro+uB9e8n1P7i+MQU5rqK40JPxKNFpkswOY9oyTCdF6tqRKpOoA7Yh5yqgbLEVSO+KCpdZotbszJyiGt2M5unZh4TJNMZK02ranAaEBO08FeOrqyJjbQLCd9NM+QJS8aUx8qIHggvX4Y/L1NWu20FLOobWQHG8DVlariaVow1H+pca2nZW78ethie44tYrM7MXu9fS5IH/4DzTG7F6McvW7y/yWPpud87R/DS4Q4Hn4R02P10Mf4iooqiBsQ4bfrHu5o1uw9xSRbFojQi+Z8NH5ADfNTBAkwOa6y7RuM56H13RZa+vHs+KuHEJ3tS7I1pQEIJZJF+vgJIOi2I2iM2nfHYhXHwOAOmpeiJChQ1BqzrGlPepqhAtAUYyXXv9l8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
