travis:
  secure:
    BINSTAR_TOKEN: Lf+qMZS4BRB/kcVWpH68it0yNvkZL+llbj7T72OWJlI7xpilKDeg9wQ8gNkXQw2cpWAZKortNJQHS9n8zvGsmktJQyd6/CG66DO7A04+jTBCIJfPgg0StQWmhxgW6USR0O6eIAogbARtzH1N2Bw9J/S/Vhl/HgRVviHrJkg/Ykrse1V8d6GnnFKIREGHYrErN7IZipQwavhOrNT6nceo8IZYgTngNwGtsXPFg8QHw2lVu3VbFOamLmxDUnpjvdy2bXXlkTkBGQREpkZ7r+cOJjjN/ABgiInlGxwjmsNru4cqI+/zy4Nblt1QSDxsuyppGJxMa5hgqCq5qhcjNZ/E60ZDCkq5gz3cSisHRHxfsraWTS27hx3w1VPs9baUThxGol8GRx+NA8RI5onbbveOOGN245NJGQ2clZfHDiNzq6QG14YksdmStQou5nblQKtpQ1ZsNe7eUYmlSjbvbhPBhUZ3dAkqO/iqGaqiK3Lt4wpfX+UtVg10MRdbm+uitku1w+57h46bzOxoHK3LUa8ZvW7ilm8e1IESqdIoAUorS3HfwNtUYEDLbqFuz7QghPga6OBIcBBKSYGJ2XBge66hwufxNSGvwuxce7lW5aMnmJIBG0k/TvoLgJl0/rkLf2BgzyXQvY/sSAcqGzsULikPpboiNOZOrvu06CYVpkqbarU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
